# version: '3.8'
services:
  web:
    restart: on-failure
    build: ./web
    networks:
      - webnet
    volumes:
      - web-build:/app/build # Store React build files in a shared volume

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - webnet
    volumes:
      - web-build:/usr/share/nginx/html
volumes:
  web-build:
networks:
  webnet: